version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: petdoc-postgres-compose
    restart: always
    environment:
      POSTGRES_DB: petdoc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: