CREATE TABLE raca (
                      id BIGSERIAL PRIMARY KEY,
                      nome VARCHAR(100) NOT NULL,
                      especie VARCHAR(50) NOT NULL
);

-- Popula a tabela com raças de Gato, focando nas mais comuns no Brasil.
INSERT INTO raca (nome, especie) VALUES
                                     ('Vira-lata (SRD)', 'Gato'),
                                     ('Abissínio', 'Gato'),
                                     ('American Curl', 'Gato'),
                                     ('American Shorthair', 'Gato'),
                                     ('Angorá Turco', 'Gato'),
                                     ('Azul Russo', 'Gato'),
                                     ('Bengal', 'Gato'),
                                     ('Birmanês', 'Gato'),
                                     ('Bobtail de Kuril', 'Gato'),
                                     ('Bobtail Japonês', 'Gato'),
                                     ('Bombay', 'Gato'),
                                     ('Britânico de Pelo Curto', 'Gato'),
                                     ('Burmese', 'Gato'),
                                     ('Chartreux', 'Gato'),
                                     ('Cornish Rex', 'Gato'),
                                     ('Cymric (Manx de pelo longo)', 'Gato'),
                                     ('Devon Rex', 'Gato'),
                                     ('Exótico', 'Gato'),
                                     ('Havana Brown', 'Gato'),
                                     ('Himalaio', 'Gato'),
                                     ('Korat', 'Gato'),
                                     ('Maine Coon', 'Gato'),
                                     ('Manx', 'Gato'),
                                     ('Mau Egípcio', 'Gato'),
                                     ('Neva Masquerade', 'Gato'),
                                     ('Norueguês da Floresta', 'Gato'),
                                     ('Ocicat', 'Gato'),
                                     ('Oriental Shorthair', 'Gato'),
                                     ('Pelo Curto Brasileiro', 'Gato'),
                                     ('Persa', 'Gato'),
                                     ('Peterbald', 'Gato'),
                                     ('Pixie-bob', 'Gato'),
                                     ('Ragdoll', 'Gato'),
                                     ('Ragamuffin', 'Gato'),
                                     ('Savannah', 'Gato'),
                                     ('Scottish Fold', 'Gato'),
                                     ('Siberiano', 'Gato'),
                                     ('Siamês', 'Gato'),
                                     ('Snowshoe', 'Gato'),
                                     ('Somali', 'Gato'),
                                     ('Sphynx', 'Gato'),
                                     ('Tonquinês', 'Gato'),
                                     ('Van Turco', 'Gato');

-- Popula a tabela com raças de Cachorro, focando nas mais comuns no Brasil.
INSERT INTO raca (nome, especie) VALUES
                                     ('Vira-lata (SRD)', 'Cachorro'),
                                     ('Akita Inu', 'Cachorro'),
                                     ('American Bully', 'Cachorro'),
                                     ('American Pit Bull Terrier', 'Cachorro'),
                                     ('Basset Hound', 'Cachorro'),
                                     ('Beagle', 'Cachorro'),
                                     ('Bichon Frisé', 'Cachorro'),
                                     ('Border Collie', 'Cachorro'),
                                     ('Boston Terrier', 'Cachorro'),
                                     ('Boxer', 'Cachorro'),
                                     ('Bull Terrier', 'Cachorro'),
                                     ('Bulldog Campeiro', 'Cachorro'),
                                     ('Bulldog Francês', 'Cachorro'),
                                     ('Bulldog Inglês', 'Cachorro'),
                                     ('Bullmastiff', 'Cachorro'),
                                     ('Chihuahua', 'Cachorro'),
                                     ('Chinese Crested', 'Cachorro'),
                                     ('Chow Chow', 'Cachorro'),
                                     ('Cocker Spaniel Inglês', 'Cachorro'),
                                     ('Corgi (Pembroke)', 'Cachorro'),
                                     ('Dachshund (Teckel/Salsicha)', 'Cachorro'),
                                     ('Dálmata', 'Cachorro'),
                                     ('Doberman', 'Cachorro'),
                                     ('Dogo Argentino', 'Cachorro'),
                                     ('Dogue Alemão', 'Cachorro'),
                                     ('Fila Brasileiro', 'Cachorro'),
                                     ('Fox Paulistinha (Terrier Brasileiro)', 'Cachorro'),
                                     ('Golden Retriever', 'Cachorro'),
                                     ('Husky Siberiano', 'Cachorro'),
                                     ('Labrador Retriever', 'Cachorro'),
                                     ('Lhasa Apso', 'Cachorro'),
                                     ('Malamute do Alasca', 'Cachorro'),
                                     ('Maltês', 'Cachorro'),
                                     ('Miniature Pinscher', 'Cachorro'),
                                     ('Norfolk Terrier', 'Cachorro'),
                                     ('Papillon', 'Cachorro'),
                                     ('Pastor Alemão', 'Cachorro'),
                                     ('Pastor Belga Malinois', 'Cachorro'),
                                     ('Pastor de Shetland', 'Cachorro'),
                                     ('Poodle', 'Cachorro'),
                                     ('Pug', 'Cachorro'),
                                     ('Rottweiler', 'Cachorro'),
                                     ('Samoieda', 'Cachorro'),
                                     ('São Bernardo', 'Cachorro'),
                                     ('Schnauzer (Miniatura)', 'Cachorro'),
                                     ('Shiba Inu', 'Cachorro'),
                                     ('Shih Tzu', 'Cachorro'),
                                     ('Spitz Alemão (Lulu da Pomerânia)', 'Cachorro'),
                                     ('Staffordshire Bull Terrier', 'Cachorro'),
                                     ('West Highland White Terrier', 'Cachorro'),
                                     ('Whippet', 'Cachorro'),
                                     ('Yorkshire Terrier', 'Cachorro');